<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pages\Accounts\**" />
    <Compile Remove="Pages\Credits\**" />
    <Compile Remove="Pages\Developers\**" />
    <Compile Remove="Pages\Messaging\**" />
    <Compile Remove="Pages\Support\**" />
    <Content Remove="Pages\Accounts\**" />
    <Content Remove="Pages\Credits\**" />
    <Content Remove="Pages\Developers\**" />
    <Content Remove="Pages\Messaging\**" />
    <Content Remove="Pages\Support\**" />
    <EmbeddedResource Remove="Pages\Accounts\**" />
    <EmbeddedResource Remove="Pages\Credits\**" />
    <EmbeddedResource Remove="Pages\Developers\**" />
    <EmbeddedResource Remove="Pages\Messaging\**" />
    <EmbeddedResource Remove="Pages\Support\**" />
    <None Remove="Pages\Accounts\**" />
    <None Remove="Pages\Credits\**" />
    <None Remove="Pages\Developers\**" />
    <None Remove="Pages\Messaging\**" />
    <None Remove="Pages\Support\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Accounts\EditProfileModal.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Messaging\SenderIds.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Messaging\Messages\Index.razor" />
    <Content Include="Pages\Messaging\Messages\ScheduledMessages.razor" />
    <Content Include="Pages\Messaging\Messages\SentMessages.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Messaging\Compose\CustomizedMessage.razor" />
    <Content Include="Pages\Messaging\Compose\Index.razor" />
    <Content Include="Pages\Messaging\Compose\SimpleMessage.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Messaging\Contacts\BulkFilesTab.razor" />
    <Content Include="Pages\Messaging\Contacts\CsvExcelTab.razor" />
    <Content Include="Pages\Messaging\Contacts\Index.razor" />
    <Content Include="Pages\Messaging\Contacts\PhonebookTab.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SMSLive247.ApiClient\SMSLive247.ApiClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.LocalStorage" Version="10.1.0" />
  </ItemGroup>

</Project>
