<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pages\Accounts\**" />
    <Compile Remove="Pages\Credits\Modals\**" />
    <Compile Remove="Pages\Messaging\**" />
    <Content Remove="Pages\Accounts\**" />
    <Content Remove="Pages\Credits\Modals\**" />
    <Content Remove="Pages\Messaging\**" />
    <EmbeddedResource Remove="Pages\Accounts\**" />
    <EmbeddedResource Remove="Pages\Credits\Modals\**" />
    <EmbeddedResource Remove="Pages\Messaging\**" />
    <None Remove="Pages\Accounts\**" />
    <None Remove="Pages\Credits\Modals\**" />
    <None Remove="Pages\Messaging\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Accounts\EditProfileModal.razor" />
    <Content Include="Pages\Messaging\Messages\Drafts.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Messaging\SenderIDs\SenderIds.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Messaging\Messages\_Index.razor" />
    <Content Include="Pages\Messaging\Messages\Scheduled.razor" />
    <Content Include="Pages\Messaging\Messages\Sent.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Messaging\Compose\Customized.razor" />
    <Content Include="Pages\Messaging\Compose\_Index.razor" />
    <Content Include="Pages\Messaging\Compose\Simple.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Messaging\Contacts\BulkFiles.razor" />
    <Content Include="Pages\Messaging\Contacts\CsvFiles.razor" />
    <Content Include="Pages\Messaging\Contacts\_Index.razor" />
    <Content Include="Pages\Messaging\Contacts\Phonebook.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Accounts\Profile.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Pages\Accounts\SubAccounts.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SMSLive247.ApiClient\SMSLive247.ApiClient.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.LocalStorage" Version="10.1.0" />
  </ItemGroup>

</Project>
